"""Export segment results to Logic Pro X via AppleScript.

Requires Logic Pro X to be installed on macOS. The exporter generates and
executes an AppleScript that creates a new project (or updates an existing
one), adds audio tracks per speaker, and imports WAV files at their correct
timeline positions.
"""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

from voice_pipeline.models import SegmentResult


def _escape_applescript_string(value: str) -> str:
    """Escape a string for safe use in AppleScript double-quoted strings."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _ms_to_smpte(ms: int) -> str:
    """Convert milliseconds to SMPTE time string (HH:MM:SS:FF at 30fps)."""
    total_seconds = ms / 1000.0
    hours = int(total_seconds // 3600)
    minutes = int((total_seconds % 3600) // 60)
    seconds = int(total_seconds % 60)
    frames = int(round((total_seconds - int(total_seconds)) * 30))
    if frames >= 30:
        frames = 29
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}:{frames:02d}"


def _generate_applescript(
    segment_results: list[SegmentResult],
    position_map: dict[tuple[str, int], int] | None,
    project_name: str,
    update_existing: bool = False,
) -> str:
    """Generate an AppleScript for Logic Pro X import.

    Args:
        segment_results: List of segment results.
        position_map: Optional position map for preserving segment start times.
        project_name: Name for the new Logic project.
        update_existing: If True, uses the frontmost project instead of creating new.

    Returns:
        The AppleScript source as a string.
    """
    # Determine speaker order and lanes
    speaker_order: list[str] = []
    for segment in segment_results:
        if segment.speaker_id not in speaker_order:
            speaker_order.append(segment.speaker_id)

    # Compute positioned segments
    positioned_segments: list[tuple[SegmentResult, int]] = []
    cursor_ms = 0
    for segment in segment_results:
        if position_map and (segment.turn_id, segment.chunk_index) in position_map:
            start_ms = position_map[(segment.turn_id, segment.chunk_index)]
        else:
            start_ms = cursor_ms
            cursor_ms += segment.duration_ms + segment.gap_after_ms
        positioned_segments.append((segment, start_ms))

    # Group segments by speaker for track-oriented import
    segments_by_speaker: dict[str, list[tuple[SegmentResult, int]]] = {
        speaker: [] for speaker in speaker_order
    }
    for segment, start_ms in positioned_segments:
        segments_by_speaker[segment.speaker_id].append((segment, start_ms))

    lines = [
        "-- Generated by voice_pipeline logic_exporter",
        "-- Import voice segments into Logic Pro X",
        "",
        'tell application "Logic Pro"',
        "    activate",
    ]

    if update_existing:
        lines.extend([
            "    -- Use the frontmost project",
            "    set proj to front project",
        ])
    else:
        lines.extend([
            f'    -- Create new project named "{_escape_applescript_string(project_name)}"',
            "    set proj to make new project",
        ])

    lines.append("")

    # Create tracks for each speaker
    for speaker_id in speaker_order:
        display_name = speaker_id.replace("_", " ").title()
        lines.extend([
            f'    -- Track for {display_name}',
            f'    tell proj',
            f'        make new audio track at end of tracks with properties {{name:"{_escape_applescript_string(display_name)}"}}',
            "    end tell",
        ])

    lines.append("")

    # Import segments per speaker
    for track_idx, speaker_id in enumerate(speaker_order, start=1):
        display_name = speaker_id.replace("_", " ").title()
        lines.extend([
            f'    -- Import segments for {display_name}',
            f'    tell track {track_idx} of proj',
        ])

        for segment, start_ms in segments_by_speaker[speaker_id]:
            wav_path = segment.wav_path.resolve().as_posix()
            smpte = _ms_to_smpte(start_ms)
            duration_s = segment.duration_ms / 1000.0

            lines.extend([
                f'        set audioFile to POSIX file "{_escape_applescript_string(wav_path)}"',
                f'        set newRegion to import audio file audioFile',
                f'        set position of newRegion to "{_escape_applescript_string(smpte)}"',
                f'        set length of newRegion to {duration_s}',
            ])

        lines.extend([
            "    end tell",
            "",
        ])

    lines.extend([
        '    display notification "Voice pipeline export complete" with title "Logic Pro"',
        "end tell",
        "",
    ])

    return "\n".join(lines)


def export_to_logic(
    segment_results: list[SegmentResult],
    position_map: dict[tuple[str, int], int] | None = None,
    project_name: str = "Voice Pipeline Export",
    update_existing: bool = False,
    dry_run: bool = False,
) -> tuple[str, str]:
    """Export segment results to Logic Pro X via AppleScript.

    Args:
        segment_results: List of segment results.
        position_map: Optional position map for preserving segment start times.
        project_name: Name for the Logic project.
        update_existing: If True, targets the frontmost project instead of creating new.
        dry_run: If True, generates the AppleScript but does not execute it.

    Returns:
        Tuple of (applescript_source, execution_output_or_error).
        If dry_run is True, execution_output_or_error is empty.

    Raises:
        RuntimeError: If Logic Pro X is not available or AppleScript execution fails.
    """
    # Check if we're on macOS and osascript is available
    if not Path("/usr/bin/osascript").exists():
        raise RuntimeError(
            "Logic Pro X export requires macOS with /usr/bin/osascript. "
            "This feature is not available on your platform."
        )

    script = _generate_applescript(
        segment_results, position_map, project_name, update_existing
    )

    if dry_run:
        return script, ""

    # Write script to temp file and execute
    with tempfile.NamedTemporaryFile(mode="w", suffix=".applescript", delete=False) as f:
        f.write(script)
        script_path = Path(f.name)

    try:
        result = subprocess.run(
            ["/usr/bin/osascript", str(script_path)],
            capture_output=True,
            text=True,
            timeout=300,  # 5 minutes - Logic import can be slow
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"AppleScript execution failed (exit {result.returncode}): "
                f"{result.stderr.strip() or result.stdout.strip()}"
            )
        return script, result.stdout.strip()
    except subprocess.TimeoutExpired:
        raise RuntimeError(
            "AppleScript execution timed out after 5 minutes. "
            "Logic Pro X may be unresponsive."
        )
    finally:
        script_path.unlink(missing_ok=True)
